Dependencies: Add `greenlet` package to `test` dependency group
All async tests apparently need it. Otherwise:

pytest -vvv -k test_async_pgvector

ValueError: the greenlet library is required to use this function. No module named 'greenlet'