Dependencies: Add `greenlet` package to `test` dependency group (#161)
All async tests apparently need it. Otherwise:

```shell
pytest -vvv -k test_async_pgvector
```
```python
ValueError: the greenlet library is required to use this function. No module named 'greenlet'
```