deps: add missing dependencies in `test` group (#223)
This PR adds missing dependencies to `pyproject.toml` test dependency
group (used for local development).
Added dependencies:

- `codespell` - required to run `make spell_check` and `make spell_fix`
scripts
- `pytest-watcher` - required to run `make test_watch`
- `greenlet` - without it, `make test` fails with error below. It was
previously added in #161, but lost at some point.
```
ValueError: the greenlet library is required to use this function. No module named 'greenlet'
```